### ISSUE TITLE
whitespace errors in template

### ISSUE THREAD

**Issue by ktdreyer** [fedora-ruby/gem2rpm#26]
This is a really small thing, but it bugs me enough to file a bug report :-)

I'm using gem2rpm 0.9.2 on Fedora 19. gem2rpm adds the following lines to the spec:

```
Requires: ruby(rubygems) 
BuildRequires: rubygems-devel 
BuildRequires: ruby 
```

Unfortunately each of these lines has a trailing whitespace. This whitespace comes from the Fedora erb template in gem2rpm. The whitespace shows up when examining a `git diff` or `git show` (and color.ui is enabled in `.gitconfig`). It's cleaner to leave the trailing whitespace out of the initial spec in the first place. This will also allow for cleaner commits and diffs down the line, since the whitespace won't need to be removed once the package has been imported into Fedora.

**Comment by strzibny** [comment]
@voxik do you have something against the following?

```ruby
<% for req in d.requirement -%>
Requires: rubygem(<%= d.name %>)<%= " #{req}" unless req.blank?  %>
<% end -%>
```

This issue annoys me as well:).

**Comment by voxik** [comment]
@strzibny Please go ahead with your proposal. Get rid of this annoyance.

You might consider implementing new template helper, since I introduced module TempalteHelper just seconds ago.
