### ISSUE TITLE
Remove deprecated templates

### ISSUE THREAD

**Issue by axilleas** [fedora-ruby/gem2rpm#30]
I see that currently there are the following templates:

```
default.spec.erb
fedora-19-21.spec.erb
fedora.spec.erb
fedora-17-18.spec.erb
fedora-21-rawhide.spec.erb
opensuse.spec.erb
```
but we only use `fedora-19-21.spec.erb` and `fedora-21-rawhide.spec.erb`. What if we removed the ones not needed?

Also, `fedora-19-21.spec.erb` should be `fedora-19-20.spec.erb`, no?

**Comment by strzibny** [comment]
Let's keep them for now, they are usuful as @voxik pointed out for RHEL packaging since the new ones do not include generated `Requires`. Not sure about default though, perhaps it could point to the newest Fedora?
