### ISSUE TITLE
Dealing with gem dependencies

### ISSUE THREAD

**Issue by ael1930** [fedora-ruby/gem2rpm#32]
Hello

This is not so much an issue with this tool, but more of a discussion of a problem we are having.

We are trying to package our gem file using gem2rpm, but we have a few dependencies that need to be satisfied. We can see that the RPM file produced has specified these dependencies correctly, but we don’t want to get into the process of generating a large number of RPMs ourselves for packages which do not belong to us. Although we are working internally at the moment, it seems this would become quite an issue in cases where the RPM would be distributed externally—it would not be correct for us to publish the RPM representing someone else’s gem.

We have considered two alternatives. The first is that we write our own spec file to simply call ‘gem install’ against a gem file contained within the RPM on installation, and then allow gem to resolve the dependencies itself at install time (although obviously this could lead to dependencies being left on the box at uninstall time).

The other option is to look at containing all the gem dependencies in our RPM in a sandboxed environment using something like [rbenv](https://github.com/sstephenson/rbenv). That way the dependencies would be available, and could be removed by rpm when the package was uninstalled, without them interfering with any other gems on the box.

Do the contributors to this tool have any opinion as to how best to deal with this problem?

George and [Mark](https://github.com/mrmanc)

**Comment by strzibny** [comment]
I believe you have sort of two options:

1. Package everything (its not really a problem package other people gems other then a lot of extra work) and expose the whole RPM repository with all your gems. That's how some Red Hat's applications and other projects (Open Build Service) are deployed. I think it's a little bit nicer options, but requires more work.

2. Bundle everything you need and its not provided by your system. In this case the package should be self-contained and not interfere with the rest of the system. You can find inspiration in Atom.io or Vagrant RPM packages, or you can use projects like https://github.com/phusion/traveling-ruby to help you with that.
