### ISSUE TITLE
not an rpm package (or package manifest) when using -o parameter

### ISSUE THREAD

**Issue by FrostyX** [fedora-ruby/gem2rpm#59]
Hi, this strange issue occurs to me.

    $ gem2rpm gem2rpm --fetch --srpm
    Wrote: /tmp/gems/rubygem-gem2rpm-0.11.3-1.fc23.src.rpm
    
    $ rpm -qpi rubygem-gem2rpm-0.11.3-1.fc23.src.rpm
    Name        : rubygem-gem2rpm
    Version     : 0.11.3
    Release     : 1.fc23
    ....

Everything above is correct. But please see this

    $ gem2rpm gem2rpm --fetch --srpm -o foo.src.rpm
    Wrote: /tmp/gems/rubygem-gem2rpm-0.11.3-1.fc23.src.rpm      <-- Wrong filename here but nvm

    $ ls foo.src.rpm
    foo.src.rpm

    $ rpm -qpi foo.src.rpm
    error: foo.src.rpm: not an rpm package (or package manifest)

Am I doing something wrong or it is a bug?

**Comment by FrostyX** [comment]
Ok, after some investigation we found out that gem2rpm can't combine `-o` and `--srpm` arguments so what I am generating with 

`gem2rpm gem2rpm --fetch --srpm -o foo.src.rpm`

is just a spec file. Thanks @voxik.

**Comment by voxik** [comment]
Seem the issue was resolved, closing this now.
