### ISSUE TITLE
Add option to specify output directory

### ISSUE THREAD

**Issue by FrostyX** [fedora-ruby/gem2rpm#60]
I would appreciate a command line argument for specifying output directory which I would like to use in conjunction with `--srpm` argument.

We settle on following idea:

Usage:

    gem2rpm <gem> --fetch --srpm -C <output_dir>

Example:

    $ gem2rpm gem2rpm --fetch --srpm -C /tmp/foo/
    $ ls /tmp/foo/
    gem2rpm-0.11.3.gem  rubygem-gem2rpm-0.11.3-1.fc23.src.rpm

So far I workaround it by changing working directory, then running `gem2rpm` and then changing working directory back to the original one, but I find the `-C` option much more elegant.

Thank you for considering this.

**Comment by junaruga** [comment]
It looks nice feature. Let me implement it!

**Comment by junaruga** [comment]
I implemented it, and requesting pull-request.

**Comment by voxik** [comment]
This should be resolved now.
