### ISSUE TITLE
--no-doc not implemented 

### ISSUE THREAD

**Issue by junaruga** [fedora-ruby/gem2rpm#70]
```
$ bin/gem2rpm --version
0.11.3
```

We can see --no-doc option.

```
$ bin/gem2rpm --help
...
        --no-doc                     Disable document subpackage
...
```

But Actually no-doc logic has not been implemented.
See doc_subpackage variable in convert method.
https://github.com/fedora-ruby/gem2rpm/blob/v0.11.3/lib/gem2rpm.rb#L44-65

**Comment by voxik** [comment]
@junaruga you should check the templates .... Actually I have not checked the functionality recently, but I believe it works ...

**Comment by junaruga** [comment]
Sorry. It was my mistake. I can see that the logic is in template files.
