### ISSUE TITLE
"exit" are called in the lib files

### ISSUE THREAD

**Issue by junaruga** [fedora-ruby/gem2rpm#74]
"exit" functions are called in lib file.
I think this is not good style.
For example, when someone want to write unit test for the class including the logic, its logic exits the process of the test suite, accidentally.

Calling fail(raise) or return looks better.

```
$ grep -r exit lib/
lib/gem2rpm/configuration.rb:      exit(1)
lib/gem2rpm/configuration.rb:        exit 0
lib/gem2rpm/configuration.rb:        exit 0
```

**Comment by voxik** [comment]
This should be resolved now.

BTW I see you referenced the issue in the commit message, but some keyword to close the associated issue automatically: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by junaruga** [comment]
@voxik ok, I will take note this. Thanks.
