### ISSUE TITLE
Suggestion: Mark up current template with "--templates"

### ISSUE THREAD

**Issue by junaruga** [fedora-ruby/gem2rpm#79]
I would like to suggest new feature to mark up the current template with "--templates".

Current "--templates" feature is like this.

```
$ bin/gem2rpm --templates
Available templates in /home/jaruga/git/gem2rpm_junaruga/lib/gem2rpm/../../templates:

default
fedora-17-18
fedora-19-20
fedora-21-rawhide-vagrant-plugin
fedora-21-rawhide
fedora
opensuse
pld
```

My suggestion is like this.

```
$ bin/gem2rpm --templates
Available templates in /home/jaruga/git/gem2rpm_junaruga/lib/gem2rpm/../../templates:

  default
  fedora-17-18
  fedora-19-20
  fedora-21-rawhide-vagrant-plugin
* fedora-21-rawhide
  fedora
  opensuse
  pld
```

```
$ bin/gem2rpm --templates vagrant-something
Available templates in /home/jaruga/git/gem2rpm_junaruga/lib/gem2rpm/../../templates:

  default
  fedora-17-18
  fedora-19-20
* fedora-21-rawhide-vagrant-plugin
  fedora-21-rawhide
  fedora
  opensuse
  pld
```

This feature was inspired from "git branch", "rbenv versions".

```
$ git branch
  develop
* feature/foo
  master
```

```
$ rbenv versions
* system
  2.2.4
  2.3.0
```

How do you think about my suggestion?

**Comment by voxik** [comment]
I'm not sure about the vagrant example, but I like this idea

**Comment by junaruga** [comment]
@voxik  thanks for your opinion.

About the vagrant example, there is vagrant specified feature in current gem2rpm.
For example, with "-T" option to get current template file content, when the gem name matching to " /^vagrant(-|_).*/" is set as a argument of gem2rpm, the vagrant specified template is used instead of common template.

```
$ bin/gem2rpm -T vagrant-env > vagrant.template.txt

$ diff vagrant.template.txt templates/fedora-21-rawhide-vagrant-plugin.spec.erb

$ echo $?
0 <= no difference. fedora-21-rawhide-vagrant-plugin.spec.erb is outputted as a current template.
```

Related code is here.
https://github.com/fedora-ruby/gem2rpm/blob/v0.11.3/lib/gem2rpm/template.rb#L30-31

**Comment by voxik** [comment]
I understand the idea, but I don't like to specify gem name just to get different default template. That looks awkward to me.

**Comment by junaruga** [comment]
@voxik okay.
I am going to implement for only below case.
```
$ bin/gem2rpm --templates
```
And if the argument is specified for "--templates" such as ```bin/gem2rpm --templates gem_name```, I may add validation check  for the case.

**Comment by voxik** [comment]
For the beginning, I implemented the basic version that just marks the template by the distribution in background.
