### ISSUE TITLE
Auto clean-up of gem2rpm-* tmpdirs with --srpm

### ISSUE THREAD

**Issue by clime** [fedora-ruby/gem2rpm#85]
Hello, it seems that the temporary directories created by gem2rpm --fetch are not cleaned up after the job is done.  One then needs lots of hard-disk space when trying to rebuild quite a few packages automatically.

**Comment by voxik** [comment]
You mean probably the --srpm option, since the --fetch should not create any temporary directory.

**Comment by clime** [comment]
Yes, probably I mean --srpm. Actually we use both in our system (--fetch --srpm) if that matters.
