### ISSUE TITLE
Fix the permissions in bin/exe according to gemspec

### ISSUE THREAD

**Issue by voxik** [fedora-ruby/gem2rpm#86]
There is new trend to put executables into exe directory instead of bin. This uncovers flaw in the default template, where the path for binaries is hardcoded in template [1] where it should be resolved from gemspec.

[1] https://github.com/fedora-ruby/gem2rpm/blob/5f5b1e4259d271ff988a0c03a579dfa1ecee7804/templates/fedora-26-rawhide-vagrant-plugin.spec.erb#L74

**Comment by shlok007** [comment]
@voxik I wish to work on this.

**Comment by voxik** [comment]
@shlok007 That would be great :+1:  Feel free to open PR. Thank you
