### ISSUE TITLE
Timing to bump version

### ISSUE THREAD

**Issue by junaruga** [fedora-ruby/gem2rpm#87]
When I checked latest version v0.11.3 and HEAD of master, I found that those template result are different, because of below feature.

https://github.com/fedora-ruby/gem2rpm/commit/3857812af8f93713369eae7d3fbd5331f898a8cb

```
Author: Elan Ruusamäe <glen@delfi.ee>
Date:   Mon May 23 19:37:49 2016 +0300

    use '>=' not '=>' in specs

    this is more rpm like version range specifier style
```

After a while we changed the result of the template, I want you to bump version.
Because users often use latest gem version not HEAD of master branch.
Is it possible?

**Comment by voxik** [comment]
Do I understand correctly that you'd like me to release new version with this change? I have not released new version, because this is not significant change IMO.

If you were asking something else, please explain. Thx.

**Comment by junaruga** [comment]
ok no problem. I close this ticket. Thanks.
