### ISSUE TITLE
Group tag is deprecated

### ISSUE THREAD

**Issue by junaruga** [fedora-ruby/gem2rpm#93]
I think that the Group tag should be removed in the future from `fedora.spec.erb`.

https://fedoraproject.org/wiki/Packaging:Guidelines#Tags_and_Sections
> The BuildRoot: tag, Group: tag, and %clean section SHOULD NOT be used.

```
$ grep -r Group templates/fedora.spec.erb 
Group: Development/Languages
Group: Documentation
Group: Development/Languages
```

**Comment by voxik** [comment]
That is just fallback template. I see no point in updating this template, since nobody is really expected to use it nowadays.

On the other hand, if you started to cleaned it up, you would eventually get the fedora-26-rawhide.spec.erb, so neither this makes sense.
